### ISSUE TITLE
Usage of the bootloader with picoprobe

### ISSUE THREAD

**Issue by amrithvenkat** [usedbytes/rp2040-serial-bootloader#10]
Hi Brian,
I am currently using your bootloader with my custom applications. I am also trying to debug my application with the Picoprobe.uf2 provided by Raspberry pi. What changes do I need to make the bootloader and the app be recogonized by openocd on the picoprobe? 
I am also trying to flash the target pico with your pico-blink-noboot2 as a sample. 
Ubuntu 20.04
VSCode extension

This is the output on the Debug console.

```
Cortex-Debug: VSCode debugger extension version 1.12.0 git(d7a405a). Usage info: https://github.com/Marus/cortex-debug#usage
Reading symbols from objdump-multiarch --syms -C -h -w /home/amrith/github_projects/RP2040-serial-bootloader/build/bootloader.elf
Reading symbols from nm-multiarch --defined-only -S -l -C -p /home/amrith/github_projects/RP2040-serial-bootloader/build/bootloader.elf
Launching GDB: gdb-multiarch -q --interpreter=mi2
    IMPORTANT: Set "showDevDebugOutput": "raw" in "launch.json" to see verbose GDB transactions here. Very helpful to debug issues or report problems
Error: nm-multiarch failed! statics/global/functions may not be properly classified: Error: spawn nm-multiarch ENOENT
    Expecting `nm` next to `objdump`. If that is not the problem please report this.
Error: objdump failed! statics/globals/functions may not be properly classified: Error: spawn objdump-multiarch ENOENT    ENOENT means program not found. If that is not the issue, please report this problem.Launching gdb-server: openocd -c "gdb_port 50000" -c "tcl_port 50001" -c "telnet_port 50002" -s /home/amrith/pico/openocd/tcl -f /home/amrith/.vscode/extensions/marus25.cortex-debug-1.12.0/support/openocd-helpers.tcl -f interface/picoprobe.cfg -f target/rp2040.cfg
    Please check TERMINAL tab (gdb-server) for output from openocd
Finished reading symbols from objdump: Time: 23 ms
Finished reading symbols from nm: Time: 19 ms
Output radix now set to decimal 10, hex a, octal 12.
Input radix now set to decimal 10, hex a, octal 12.
0x200002ca in uart_read_blocking.constprop ()
Program stopped, probably due to a reset and/or halt issued by debugger
target halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
target halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
target halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
target halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00

Thread
1 stopped.
0x000000ea in ?? ()
```

Thanks in advance.
Regards,
Amrith

**Comment by felixdoerre** [comment]
The bootloader elf file can be used, flashed, and debugged like any other application, in fact it just behaves just like any other application, apart from the fact that it later jumps into another binary.

Did you have picoprobe debugging working with any other program? 
From the output `pc: 0x000000ea` seems very wrong, because as far as I know there should be no code in that memory region, and `Error: nm-multiarch failed` also doesn't look too healthy, but that looks like a VSCode specific issue:
https://github.com/raspberrypi/pico-feedback/issues/269

Just for reference: I am using the wifi variant of this bootloader ( https://github.com/usedbytes/picowota ) together with plain gdb and picoprobe, and it works just fine.

**Comment by usedbytes** [comment]
This looks like a problem with the VS Code environment rather than the bootloader. I'll close this, if you are successfully debugging other applications and something happens differently with the bootloader, please provide some more info.
