### ISSUE TITLE
A Thank You Message

### ISSUE THREAD

**Issue by NeusAap** [usedbytes/rp2040-serial-bootloader#6]
Hello, I know this is not an issue, but I wanted to thank you for your great bootloader + serial flashing application (I could not find a comment section in your blog post, or an email address to send it to).

It has saved us loads of headaches, and we are happily using the C bootloader application!
Since we usually don't have GoLang as dependency in our deployment systems, I have rewritten your GoLang app in Python.

For now, we only needed the UART part of your implementation, so no TCP OTA updates (yet) unfortunately. It can be found here: https://github.com/ConfedSolutions/pico-py-serial-flash.

Anyways, massive thank you for the insightful blog post and helpful repositories :)

**Comment by usedbytes** [comment]
Thanks, glad it helped you - I will add your python client to the README
